// Glossario / Codice Operativo Voltra
// 40+ termini ufficiali (da deliverable Opus)

export const GLOSSARY = [
  { term: 'Albo d\'Onore', def: 'Registro pubblico dell\'organico e delle onorificenze conferite. Anonimizzato per default.' },
  { term: 'Anzianità', def: 'Tempo trascorso dall\'arruolamento, espresso in giorni. Determina alcune onorificenze automatiche.' },
  { term: 'Arruolamento', def: 'Momento formale dell\'ammissione di un nuovo membro nell\'organico, segnato dalla matricola.' },
  { term: 'Avamposto', def: 'Posizione iniziale del Caporale. Punto di partenza del servizio.' },
  { term: 'Briefing', def: 'Comunicazione del Comando. Si esprime tramite Ordini del Giorno pubblicati in Sala Briefing.' },
  { term: 'Caporale', def: 'Primo grado dell\'organico Voltra. La trincea, l\'ultimo avamposto. Constantia ante omnia.' },
  { term: 'Capitano', def: 'Terzo grado. Conduce operazioni autonome. Le Acque Profonde. Videre, deinde agere.' },
  { term: 'Cerimonia di Imposizione', def: 'Sequenza formale al primo accesso dopo l\'attribuzione o l\'avanzamento di grado.' },
  { term: 'Codice di Condotta', def: 'Cinque consegne formali per ciascun grado. Lette in Cerimonia. Vincolanti.' },
  { term: 'Codice Operativo', def: 'Insieme di termini e procedure ufficiali del club. Glossario operativo.' },
  { term: 'Colonnello', def: 'Quarto e ultimo grado. L\'Ultima Linea. Exemplo, non verbis.' },
  { term: 'Comando', def: 'Voce ufficiale che si rivolge ai membri. Riservato. Non è il fondatore: è la posizione.' },
  { term: 'Decorazione', vedi: 'Onorificenza' },
  { term: 'Dotazione', def: 'Capitale operativo associato al grado. Definito dalla posizione, non negoziabile.' },
  { term: 'Encomio', def: 'Atto di lode formale del Comando. Pubblicato in Ordine del Giorno se di rilievo.' },
  { term: 'Fascicolo Personale', def: 'Documento di servizio del membro. Identità, onorificenze, ruolino. Privato.' },
  { term: 'Grado', def: 'Posizione nell\'organico. Quattro in totale: Caporale, Sergente, Capitano, Colonnello.' },
  { term: 'Imposizione', vedi: 'Cerimonia di Imposizione' },
  { term: 'Linea', def: 'Indirizzo di posta del membro. Canale di comunicazione formale tra il Comando e l\'individuo.' },
  { term: 'Linea Diretta HQ', def: 'Canale di contatto privilegiato verso il Comando. Telegram dedicato.' },
  { term: 'Matricola', def: 'Identificativo univoco del membro. Formato VLT-XXXX. Assegnata all\'arruolamento, mai più cambiata.' },
  { term: 'Membro', def: 'Termine generico per chi è ammesso nell\'organico. Mai "utente", mai "cliente".' },
  { term: 'Menzione di Discrezione', def: 'Onorificenza silenziosa: conferita senza pubblicazione, registrata solo nel Fascicolo.' },
  { term: 'Messaggero', def: 'Designazione del Sergente. Trasmette ordini, non li interpreta. Clarius, deinde firmius.' },
  { term: 'Missione', def: 'Operazione di servizio. Ogni grado ha la propria missione caratteristica.' },
  { term: 'Onorificenza', def: 'Riconoscimento formale conferito dal Comando per merito specifico o per anzianità.' },
  { term: 'Ordine del Giorno (OdG)', def: 'Forma ufficiale di comunicazione del Comando. Numerato progressivamente.' },
  { term: 'Organico', def: 'Insieme dei membri attivi del club Voltra in un dato momento.' },
  { term: 'Promozione di Grado', def: 'Avanzamento al grado superiore. Atto formale, mai automatico.' },
  { term: 'Quartier Generale', def: 'Pannello principale del membro. Stato di servizio, comunicazioni, attivazioni.' },
  { term: 'Rapporto del Comandante', def: 'Sintesi settimanale pubblicata dal Comando. Lunedì 06:00 UTC.' },
  { term: 'Rimborso Missione', def: 'Restituzione periodica delle competenze maturate. Non è "prelievo", non è "pagamento".' },
  { term: 'Roster', def: 'Sezione pubblica dell\'Albo. Mostra solo i membri che hanno consentito la visibilità.' },
  { term: 'Ruolino di Servizio', def: 'Storico cronologico degli eventi personali del membro. Cresce nel tempo.' },
  { term: 'Sala Briefing', def: 'Spazio di pubblicazione degli Ordini del Giorno. Visibile a tutti i membri.' },
  { term: 'Sergente', def: 'Secondo grado. Il Messaggero, intermediario tra Comando e Caporali.' },
  { term: 'Servizio', def: 'Periodo di attività attiva di un membro nell\'organico. Misurato in giorni.' },
  { term: 'Sigillo del Fondatore', def: 'Onorificenza eccezionale, una sola volta nella storia del club a ciascun membro che ne sia ritenuto degno.' },
  { term: 'Silentio agimus', def: 'Motto generale del club. "Agiamo nel silenzio". Disciplina della discrezione.' },
  { term: 'Smobilitazione', def: 'Disconnessione dalla sessione attiva. Termine ufficiale per il logout.' },
  { term: 'Stato Maggiore', def: 'Sezione di comando riservata agli Amministratori. Non visibile ai membri ordinari.' },
  { term: 'Stella di Anzianità', def: 'Onorificenza automatica conferita al raggiungere milestone di servizio (Bronzo 100gg, Argento 365gg, Oro 1000gg).' },
  { term: 'Telegram Operativo', def: 'Canale di trasmissione per le ricevute di pagamento e i contatti immediati.' },
  { term: 'TxHash', def: 'Identificativo della transazione blockchain associata al pagamento. Tracciabile, verificabile.' },
  { term: 'VLT', def: 'Prefisso ufficiale delle matricole Voltra.' },
]
